In [2]:
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)

Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union


Warning message:
"package 'ggplot2' was built under R version 4.3.3"

# 1. Data

## Main Dataset - BLS LAUS Data

In [13]:
df <- read_excel(
  "../data/ststdsadata.xlsx",
  skip     = 8,
  col_names = FALSE
)

fips_to_abbr <- c(
  "01"="AL","02"="AK","04"="AZ","05"="AR","06"="CA",
  "08"="CO","09"="CT","10"="DE","12"="FL","13"="GA",
  "15"="HI","16"="ID","17"="IL","18"="IN","19"="IA",
  "20"="KS","21"="KY","22"="LA","23"="ME","24"="MD",
  "25"="MA","26"="MI","27"="MN","28"="MS","29"="MO",
  "30"="MT","31"="NE","32"="NV","33"="NH","34"="NJ",
  "35"="NM","36"="NY","37"="NC","38"="ND","39"="OH",
  "40"="OK","41"="OR","42"="PA","44"="RI","45"="SC",
  "46"="SD","47"="TN","48"="TX","49"="UT","50"="VT",
  "51"="VA","53"="WA","54"="WV","55"="WI","56"="WY"
)

df <- df  %>%
  select(fips = 1, state_name = 2, year = 3, month = 4, pop=6, unemp_pop = 10, ur = 11) %>%
  filter(
    !is.na(fips),
    !is.na(ur),
    fips %in% names(fips_to_abbr)
  ) %>%
  mutate(
    state = fips_to_abbr[fips],
    year  = as.integer(year),
    month = as.integer(month),
    pop   = as.integer(pop),
    unemp_pop = as.integer(unemp_pop),
    ur    = as.numeric(ur),
    date  = as.Date(paste(year, month, "01", sep = "-"))
  ) %>%
  select(state, date, population = pop, unemployed_population = unemp_pop, unemployment_rate = ur) %>% 
  filter(date >= as.Date("2000-01-01"), date <= as.Date("2025-12-01")) %>%
  arrange(state, date)

Warning message:
"Expecting numeric in E31650 / R31650C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31650 / R31650C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31650 / R31650C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31650 / R31650C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31650 / R31650C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31650 / R31650C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31650 / R31650C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31651 / R31651C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31651 / R31651C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31651 / R31651C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31651 / R31651C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31651 / R31651C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31651 / R31651C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31651 / R31651C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31652 / R31652C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31652 / R31652C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31652 / R31652C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31652 / R31652C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31652 / R31652C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31652 / R31652C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31652 / R31652C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31653 / R31653C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31653 / R31653C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31653 / R31653C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31653 / R31653C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31653 / R31653C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31653 / R31653C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31653 / R31653C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31654 / R31654C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31654 / R31654C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31654 / R31654C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31654 / R31654C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31654 / R31654C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31654 / R31654C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31654 / R31654C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31655 / R31655C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31655 / R31655C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31655 / R31655C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31655 / R31655C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31655 / R31655C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31655 / R31655C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31655 / R31655C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31656 / R31656C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31656 / R31656C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31656 / R31656C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31656 / R31656C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31656 / R31656C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31656 / R31656C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31656 / R31656C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31657 / R31657C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31657 / R31657C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31657 / R31657C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31657 / R31657C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31657 / R31657C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31657 / R31657C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31657 / R31657C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31658 / R31658C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31658 / R31658C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31658 / R31658C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31658 / R31658C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31658 / R31658C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31658 / R31658C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31658 / R31658C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31659 / R31659C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31659 / R31659C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31659 / R31659C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31659 / R31659C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31659 / R31659C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31659 / R31659C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31659 / R31659C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31660 / R31660C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31660 / R31660C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31660 / R31660C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31660 / R31660C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31660 / R31660C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31660 / R31660C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31660 / R31660C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31661 / R31661C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31661 / R31661C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31661 / R31661C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31661 / R31661C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31661 / R31661C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31661 / R31661C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31661 / R31661C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31662 / R31662C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31662 / R31662C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31662 / R31662C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31662 / R31662C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31662 / R31662C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31662 / R31662C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31662 / R31662C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31663 / R31663C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31663 / R31663C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31663 / R31663C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31663 / R31663C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31663 / R31663C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31663 / R31663C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31663 / R31663C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31664 / R31664C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31664 / R31664C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31664 / R31664C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31664 / R31664C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31664 / R31664C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31664 / R31664C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31664 / R31664C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31665 / R31665C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31665 / R31665C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31665 / R31665C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31665 / R31665C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31665 / R31665C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31665 / R31665C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31665 / R31665C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31666 / R31666C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31666 / R31666C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31666 / R31666C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31666 / R31666C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31666 / R31666C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31666 / R31666C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31666 / R31666C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31667 / R31667C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31667 / R31667C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31667 / R31667C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31667 / R31667C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31667 / R31667C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31667 / R31667C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31667 / R31667C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31668 / R31668C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31668 / R31668C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31668 / R31668C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31668 / R31668C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31668 / R31668C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31668 / R31668C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31668 / R31668C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31669 / R31669C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31669 / R31669C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31669 / R31669C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31669 / R31669C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31669 / R31669C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31669 / R31669C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31669 / R31669C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31670 / R31670C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31670 / R31670C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31670 / R31670C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31670 / R31670C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31670 / R31670C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31670 / R31670C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31670 / R31670C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31671 / R31671C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31671 / R31671C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31671 / R31671C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31671 / R31671C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31671 / R31671C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31671 / R31671C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31671 / R31671C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31672 / R31672C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31672 / R31672C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31672 / R31672C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31672 / R31672C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31672 / R31672C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31672 / R31672C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31672 / R31672C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31673 / R31673C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31673 / R31673C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31673 / R31673C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31673 / R31673C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31673 / R31673C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31673 / R31673C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31673 / R31673C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31674 / R31674C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31674 / R31674C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31674 / R31674C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31674 / R31674C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31674 / R31674C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31674 / R31674C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31674 / R31674C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31675 / R31675C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31675 / R31675C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31675 / R31675C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31675 / R31675C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31675 / R31675C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31675 / R31675C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31675 / R31675C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31676 / R31676C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31676 / R31676C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31676 / R31676C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31676 / R31676C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31676 / R31676C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31676 / R31676C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31676 / R31676C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31677 / R31677C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31677 / R31677C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31677 / R31677C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31677 / R31677C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31677 / R31677C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31677 / R31677C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31677 / R31677C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31678 / R31678C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31678 / R31678C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31678 / R31678C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31678 / R31678C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31678 / R31678C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31678 / R31678C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31678 / R31678C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31679 / R31679C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31679 / R31679C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31679 / R31679C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31679 / R31679C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31679 / R31679C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31679 / R31679C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31679 / R31679C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31680 / R31680C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31680 / R31680C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31680 / R31680C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31680 / R31680C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31680 / R31680C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31680 / R31680C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31680 / R31680C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31681 / R31681C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31681 / R31681C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31681 / R31681C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31681 / R31681C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31681 / R31681C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31681 / R31681C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31681 / R31681C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31682 / R31682C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31682 / R31682C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31682 / R31682C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31682 / R31682C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31682 / R31682C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31682 / R31682C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31682 / R31682C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31683 / R31683C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31683 / R31683C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31683 / R31683C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31683 / R31683C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31683 / R31683C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31683 / R31683C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31683 / R31683C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31684 / R31684C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31684 / R31684C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31684 / R31684C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31684 / R31684C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31684 / R31684C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31684 / R31684C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31684 / R31684C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31685 / R31685C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31685 / R31685C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31685 / R31685C7: got '<e2><80><93>'"
Warning message:
"Expecting numeric in H31685 / R31685C8: got '<e2><80><93>'"
Warning message:
"Expecting numeric in I31685 / R31685C9: got '<e2><80><93>'"
Warning message:
"Expecting numeric in J31685 / R31685C10: got '<e2><80><93>'"
Warning message:
"Expecting numeric in K31685 / R31685C11: got '<e2><80><93>'"
Warning message:
"Expecting numeric in E31686 / R31686C5: got '<e2><80><93>'"
Warning message:
"Expecting numeric in F31686 / R31686C6: got '<e2><80><93>'"
Warning message:
"Expecting numeric in G31686 / R31686C7: got '<e2><80><93>'"
Warning message:

quick data quality check

In [11]:
df %>%
  group_by(state) %>%
  summarise(
    first = min(date),
    last  = max(date),
    n     = n()
  ) %>%
  filter(n != 312) %>%
  arrange(n)

   state first      last       n
1  AK    2000-01-01 2025-12-01 311
2  AL    2000-01-01 2025-12-01 311
3  AR    2000-01-01 2025-12-01 311
4  AZ    2000-01-01 2025-12-01 311
5  CA    2000-01-01 2025-12-01 311
6  CO    2000-01-01 2025-12-01 311
7  CT    2000-01-01 2025-12-01 311
8  DE    2000-01-01 2025-12-01 311
9  FL    2000-01-01 2025-12-01 311
10 GA    2000-01-01 2025-12-01 311
11 HI    2000-01-01 2025-12-01 311
12 IA    2000-01-01 2025-12-01 311
13 ID    2000-01-01 2025-12-01 311
14 IL    2000-01-01 2025-12-01 311
15 IN    2000-01-01 2025-12-01 311
16 KS    2000-01-01 2025-12-01 311
17 KY    2000-01-01 2025-12-01 311
18 LA    2000-01-01 2025-12-01 311
19 MA    2000-01-01 2025-12-01 311
20 MD    2000-01-01 2025-12-01 311
21 ME    2000-01-01 2025-12-01 311
22 MI    2000-01-01 2025-12-01 311
23 MN    2000-01-01 2025-12-01 311
24 MO    2000-01-01 2025-12-01 311
25 MS    2000-01-01 2025-12-01 311
26 MT    2000-01-01 2025-12-01 311
27 NC    2000-01-01 2025-12-01 311
28 ND    2000-01-01 2025-12-01 311
29 NE    2000-01-01 2025-12-01 311
30 NH    2000-01-01 2025-12-01 311
31 NJ    2000-01-01 2025-12-01 311
32 NM    2000-01-01 2025-12-01 311
33 NV    2000-01-01 2025-12-01 311
34 NY    2000-01-01 2025-12-01 311
35 OH    2000-01-01 2025-12-01 311
36 OK    2000-01-01 2025-12-01 311
37 OR    2000-01-01 2025-12-01 311
38 PA    2000-01-01 2025-12-01 311
39 RI    2000-01-01 2025-12-01 311
40 SC    2000-01-01 2025-12-01 311
41 SD    2000-01-01 2025-12-01 311
42 TN    2000-01-01 2025-12-01 311
43 TX    2000-01-01 2025-12-01 311
44 UT    2000-01-01 2025-12-01 311
45 VA    2000-01-01 2025-12-01 311
46 VT    2000-01-01 2025-12-01 311
47 WA    2000-01-01 2025-12-01 311
48 WI    2000-01-01 2025-12-01 311
49 WV    2000-01-01 2025-12-01 311
50 WY    2000-01-01 2025-12-01 311

### Showcase data

In [14]:
head(df)
tail(df)

nrow(df) # should be 50*26*12 - 50 = 15500 rows since 2025-10-01 is missing for all states

  state date       population unemployed_population unemployment_rate
1 AK    2000-01-01 318726     19623                 6.2
2 AK    2000-02-01 319118     19758                 6.2
3 AK    2000-03-01 319507     19923                 6.2
4 AK    2000-04-01 319813     20106                 6.3
5 AK    2000-05-01 319969     20266                 6.3
6 AK    2000-06-01 319938     20354                 6.4

  state date       population unemployed_population unemployment_rate
1 WY    2025-06-01 291960     9696                  3.3
2 WY    2025-07-01 291172     9548                  3.3
3 WY    2025-08-01 290472     9384                  3.2
4 WY    2025-09-01 290192     9472                  3.3
5 WY    2025-11-01 289848     9724                  3.4
6 WY    2025-12-01 289997     9914                  3.4

[1] 15550

## National Covariate Data

### Federal Funds Rate

In [6]:
fedfunds_df <- read.csv("../data/FEDFUNDS.csv") %>%
  mutate(
    date     = as.Date(observation_date),
    fed_rate = as.numeric(FEDFUNDS)
  ) %>%
  select(date, fed_rate) |>
  filter(date >= as.Date("2000-01-01"),
         date <= as.Date("2025-12-01"))

head(fedfunds_df)
tail(fedfunds_df)

# 312 rows = 26 years * 12 months

  date       fed_rate
1 2000-01-01 5.45
2 2000-02-01 5.73
3 2000-03-01 5.85
4 2000-04-01 6.02
5 2000-05-01 6.27
6 2000-06-01 6.53

    date       fed_rate
307 2025-07-01 4.33
308 2025-08-01 4.33
309 2025-09-01 4.22
310 2025-10-01 4.09
311 2025-11-01 3.88
312 2025-12-01 3.72

###  Real GDP growth (quarterly -> interpolate to monthly)

In [8]:
gdp_raw <- read.csv("../data//REALGDP.csv") %>%
  mutate(
    date       = as.Date(observation_date),
    gdp_growth = as.numeric(A191RL1Q225SBEA)
  ) %>%
  select(date, gdp_growth) %>%
  filter(!is.na(gdp_growth))

# Method of interpolation: each month gets the value of its quarter
monthly_dates <- seq(as.Date("2000-01-01"),
                     as.Date("2025-12-01"), by = "month")
                     
gdp_df <- data.frame(date = monthly_dates) %>%
  mutate(
    gdp_growth = gdp_raw$gdp_growth[
      findInterval(date, gdp_raw$date)
    ]
  )

head(gdp_df)
tail(gdp_df)

  date       gdp_growth
1 2000-01-01 1.5
2 2000-02-01 1.5
3 2000-03-01 1.5
4 2000-04-01 7.5
5 2000-05-01 7.5
6 2000-06-01 7.5

    date       gdp_growth
307 2025-07-01 4.4
308 2025-08-01 4.4
309 2025-09-01 4.4
310 2025-10-01 0.7
311 2025-11-01 0.7
312 2025-12-01 0.7

## Export all cleaned data as CSVs for reproducable use

In [9]:
write.csv(df, "../cleaned_data/bls_data.csv", row.names = FALSE)
write.csv(fedfunds_df, "../cleaned_data/fedfunds_data.csv", row.names = FALSE)
write.csv(gdp_df, "../cleaned_data/gdp_data.csv", row.names = FALSE)